//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp20.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Digital : Instruments
    {
        public string Strike { get; set; }
        public string IsCall { get; set; }
        public string ExpirationDate { get; set; }
        public string Rebate { get; set; }
    }
}
