//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp20.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string ClosingPrice { get; set; }
        public string InstID { get; set; }
        public int InstrumentsId { internal get; set; }
    
        public virtual Instruments Instrument { get; set; }
    }
}
