//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp20.Properties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trade
    {
        public int Id { get; set; }
        public string IsBuy { get; set; }
        public string Direction { get; set; }
        public string Quantity { get; set; }
        public string Price { get; set; }
        public string TimeStamp { get; set; }
        public int InstrumentsId { get; set; }
    
        public virtual Instruments Instrument { get; set; }
    }
}
